plugins:
  - jest
  - babel
  - react
  - functional

env:
  node: true
  browser: true
  jest: true

parser: babel-eslint

extends:
  - airbnb
  - "plugin:jest/recommended"
  - "plugin:functional/external-recommended"
  - "plugin:functional/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"

settings:
  react:
    createClass: createReactClass
    pragma: React
    fragment: Fragment
    version: detect
    flowVersion: '0.53'
  propWrapperFunctions:
  - forbidExtraProps
  - property: freeze
    object: Object
  - property: myFavoriteWrapper
  linkComponents:
  - Hyperlink
  - name: Link
    linkAttribute: to


rules:
  no-console: 0
  import/extensions: [error, always, {ignorePackages: true} ]
